apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "helm-k8s-learn.labels" . | nindent 4 }}
  name: {{ include "helm-k8s-learn.fullname" . }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 80
  selector:
    {{- include "helm-k8s-learn.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
